project:
  type: website
  output-dir: docs

website:
  title: "Github Portfolio of Libby Smith"
  margin-footer: |
   ![ ](/utdfooter.jpg)

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: CV
      - href: writing.qmd
        text: Analysis Writing
      - text: Methods of Data Collection
        menu: 
          - href: assignment1.qmd
            text: Create a Qualtrics Survey
          - href: assignment2.qmd
            text: Google Trends VS Rstudio gtrends
          - href: assignment3.qmd
            text: Latent Semantic Text Analysis
          - href: assignment5.qmd
            text: Web Scraping for Word Clouds
          - href: assignment6.qmd
            text: Scraping Government Data
          - href: assignment7.qmd
            text: API Requests of Public Data
      - text: Independent Projects
        menu:
          - href: datacollectionproject.qmd
            text: AAPI in the News - NLP Machine Learning
      - text: Graphics and Visualizations
        menu:
          - href: lab1.qmd
            text: The Statistical Importance of Graphics
          - href: lab1b.qmd
            text: Critiquing Graphics
          - href: lab2.qmd
            text: Selecting Graphical Data
          - href: lab3.qmd
            text: Plot Design in R
          - href: lab3b.qmd
            text: When Big Data Goes Bad. A Critique

          
format:
  html:
    theme: spacelab
    light: flatly
    dark: darkly
    css: styles.css
    toc: true

editor: visual

