---
title: "CV/Resume"
---

# Liberty "Libby" Smith

"Knowledge will give you power, but character respect." - Bruce Lee

#### **EDUCATION**

-   **The University of Texas at Dallas,** (M.S., Social Data Analytics and Research) December 2024

Hypothesis testing, Predictive modeling, clustering, R & Python

-   **The University of Texas at Dallas,** (Bachelor of Arts in Political Science) May 2017

#### **RELEVANT EXPERIENCE**

**Suitsupply**, Dallas, Texas, USA ( Web Sales and Customer Service Analyst) Dec 2021 - Present

-   Provide growth-oriented b2c reporting focusing on their e-commerce KPIs, growth campaigns, and brick&mortar customer journeys.

-   Report quantitative business intelligence and visualizations via R and Python, discovered insights using store reviews, salesforce, and product data. IE: text/sentiment analysis of store reviews, client segmentation, and customer churn forecasting.

-   Facilitated training on product knowledge and store services. Monitored store performance, execution, and conflict resolution.

-   SalesForce developer functions including data integrity of b2c customer engagement, customization, customer service flow, and automation of repetitive tasks.

-   Project management, task triaging, and delegation.

-   Collaboration across mulitple departments to address complaint management and client relations.

-   Earned the rating of 'Exceptional' for 2 consecutive years and recognized among the top performers in the branch office.

**Korea Economic Institute of America**, Washington, D.C., USA (Economic Intern) Sept 2018 - Jan 2019

-   Led and assisted in foreign policy pieces published on "The Peninsula" -- our think-tank-sponsored blog -- alongside legacy media journalists and diplomats. Read more [here](https://libertysmith.github.io/datacollectionmethods/writing.html)

-   Collaborate with stakeholders gauged the value of Korea-US foreign trade and social policy recommendations. Advocated policy directions for equitable outcomes in economic and social matters.

-   Social media management and organizational reporting of engagement metrics on Twitter, Facebook, SproutSocial, and SurveyMonkey.

#### **EXTRA-CURRICULAR ACTIVITIES**

-   **Acts of Kindness at UTD --** Founder and Treasurer Fall 2014 - Spring 2016

    -   With a team of 12 members, proposed budgets, organized the Council events, led presentations to advocate awareness on campus, coordinated Acts of Kindness drives supporting students struggling financially during exam weeks.

    -   Promoted inter and intra-college participation by strategizing existing modes of communication, created online presence, and multiplied reach utilizing social media.

#### **ADDITIONAL INFORMATION**

Technical Skills: MySQL Certificate, R, HTML, CSS, Google Analytics, Adobe Analytics, SalesForce Developer rights, Python, MS Project Professional, MS Office, Agile Methodology, Project Management, Predictive and Statistical modeling, probability modeling, research and brief writing.

Languages: Advanced English and Conversational Korean

Eligibility: U.S. Citizen Authorized to work in the United States
